name: Github action
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create linux-chrome directory and install Chrome
        run: |
          mkdir -p ./linux-chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          dpkg -x google-chrome-stable_current_amd64.deb ./linux-chrome
          chmod -R 755 ./linux-chrome
          rm google-chrome-stable_current_amd64.deb

      - name: Get Chrome executable path
        id: chrome-path
        run: |
          CHROME_EXECUTABLE_PATH=$(find $PWD/linux-chrome -name google-chrome)
          echo "CHROME_EXECUTABLE_PATH=$CHROME_EXECUTABLE_PATH" >> $GITHUB_ENV
          echo "Chrome executable path: $CHROME_EXECUTABLE_PATH"

# jobs:
#   Run-application: 
#     runs-on: ubuntu-latest
#     steps:   
#      - name: Install dependency
#        uses: actions/checkout@v4
#      - run: npm install  

#      - name: Run Project
#        uses: actions/checkout@v4
#      - run: npm install   
#     #  - run: npm run start   

#      - name: Build Project
#        uses: actions/  @v4
#      - run: echo "Project build successfully"  
    
